build: false

image: Visual Studio 2022

environment:
    matrix:
        - PYTHON: "C:\\Python313-x64"
        - PYTHON: "C:\\Python314-x64"

#matrix:
#    allow_failures:

init:
  - SET PATH=%PYTHON%;%PATH%
  - SET UV_PYTHON=%PYTHON%\python.exe

install:
    - ps: irm https://astral.sh/uv/install.ps1 | iex
    - SET PATH=%USERPROFILE%\.local\bin;%PATH%
    - uv sync --all-groups

test_script:
    - uv run pytest --cov=./ --mypy -vv
    - uv run coverage xml -i
