engines:
    pylint:
        enabled: true
        python_version: 3.9
exclude_paths:
    - '**.md'
    - '**.yml'
    - '**.txt'
    - 'test_suite/**'
coverage:
    enabled: true
    exclude_paths:
        - '**.md'
        - '**.yml'
        - '**.txt'
        - 'test_suite/**'
