[project]
name = "dionysus"
version = "0.1.0"
description = "Student avatar chart generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib==3.10.8",
    "pillow==12.0.0",
    "sqlalchemy==2.0.44",
]

[dependency-groups]
testing = [
    "coverage==7.13.0",
    "mypy==1.19.1",
    "pre-commit==4.5.0",
    "pytest==9.0.1",
    "pytest-cov==7.0.0",
    "pytest-mypy==1.0.1",
    "ruff==0.14.9",
]

[tool.hatch.build.targets.wheel]
packages = ["dionysus_app"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
