[project]
name = "dionysus"
version = "0.1.0"
description = "Student avatar chart generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib==3.10.8",
    "pillow==12.2.0",
    "sqlalchemy==2.0.48",
]

[dependency-groups]
testing = [
    "coverage==7.13.5",
    "mypy==1.20.0",
    "pre-commit==4.5.1",
    "pytest==9.0.2",
    "pytest-cov==7.1.0",
    "pytest-mypy==1.0.1",
    "ruff==0.15.9",
]

[tool.hatch.build.targets.wheel]
packages = ["dionysus_app"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
