name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}  # continue after failures
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]
        experimental: [false]  # These versions must pass.
        
        include:
          - python-version: 3.6
            os: ubuntu_latest 
            experimental: true
          - python-version: 3.7
            os: ubuntu_latest 
            experimental: true
          - python-version: 3.10.0-dev
            os: ubuntu_latest 
            experimental: true
          
          - python-version: 3.6
            os: windows_latest 
            experimental: true
          - python-version: 3.7
            os: windows_latest
            experimental: true
          - python-version: 3.10.0-dev
            os: windows_latest
            experimental: true

    steps:
    - uses: actions/checkout@v2  # checkout repo
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_dev.txt

    - name: Test with pytest --cov=./ --mypy -vv
      run: |
        pytest --cov=./ --mypy -vv
        coverage xml -i

    - name: Codacy Coverage Reporter
      #uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
          run: python-codacy-coverage -r coverage.xml
        
    - name: Codecov  # upload 
      uses: codecov/codecov-action@v1.2.1
      with:
        files: ./coverage1.xml
        name: codecov-umbrella # optional
        fail_ci_if_error: false # allow codecov to signal fail rather than action failing.
        verbose: true # optional (default = false)

    
    
